"""empty message

Revision ID: 2f53590d4db8
Revises: 42008b77dba1
Create Date: 2024-06-21 22:20:48.517495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f53590d4db8'
down_revision = '42008b77dba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))
        batch_op.alter_column('category_name',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('category_name',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
        batch_op.drop_column('color')

    # ### end Alembic commands ###
